### ISSUE TITLE
Implement Talon Factory

### ISSUE THREAD

**Issue by pdeutsch** [TheGreenMachine/Zeta#14]
It would be desirable make the Zeta code work on robots that are in intermediate states of build (missing subsystems) and also work on Zenith.  One problem is that we have to instantiate all subsystems, but we will get error messages if a Talon doesn't exist when the subsystem is created.

One way to do this would be to store all the robot information in a properties file that lives on each robot. This file would contain flags on whether the subsystem is implemented and details about which talon number is being used.

One problem is that we still have to setup the Talons even if they don't exist. It should be possible to use dummy Talon classes that implement the IMotorController interface.

- Create a GhostTalon class that implements IMotorController. It should have println's whenever a "setXXX" method is called and return appropriate values. Mr. Day might have this class already.
- Create a factory method to get Talons.  The factory will load the robot properties file at startup and either return a TalonSRX class with all defaults set, or a GhostTalon class.
- Modify the subsystem classes to use IMotorController interface instead of TalonSRX.

Here is some example code of one way this could be done

```java
   public class Drivetrain {
       private IMotorController leftMain;
       ...

      public Drivetrain() {
         leftMain = RobotFactory.getInstance().getTalon("drivetrain", "leftMain");
```

```java
   public class RobotFactory {
      private Properties robotProperties;
      private RobotFactory instance = new RobotFactory();

      private RobotFactory() {
         // code goes here to read properties and store in robotProperties
      }

      public static getInstance() { return instance; }

      public IMotorController getTalon(String subsystem, String talonId) {
         // if subsystem exists return TalonSRX else return GhostTalon
      }

      public boolean isImplemented(String subsystem) {
         // code to see if subsystem exists in robotProperties and is "true"
      }
```

```properties
drivetrain = true
leftMain = 1
leftSlaveOne = 2
...

beak = false

cargoShooter = true
arm = 6
intake = 9
```

- [x] Initial development of Robot and Talon factories
- [x] Add support for VictorSPX

**Comment by richiksc** [comment]
I've created a branch [feature/talon-factory](/TheGreenMachine/Zeta/tree/feature/talon-factory) for this issue. However, I am not taking ownership of this issue (yet) unless I'm assigned to do so.

**Comment by richiksc** [comment]
What if we used Yaml configuration for more readability and structure? Would probably be easier to parse as well.

```yaml
drivetrain:
  implemented: true
  talons:
    leftMain: 1
    leftSlaveOne: 2
```

And also, sometimes the subsystem might exist but the talon might not, in that case we should return a ghost talon.

**Comment by richiksc** [comment]
I've got a simple version up and running. Just tested Zeta code on Zenith - checker framework also tested.
